name = "FemtoJuliaGreenRegistry"
uuid = "bee36106-d005-43ac-85f3-ba916459c0ee"
repo = "git@github.com:femtotrader/FemtoJuliaGreenRegistry.git"
description = "My green registry"

[packages]
da7a6f3e-f359-4376-82ed-d2d5f3be0019 = { name = "ParquetStores", path = "P/ParquetStores" }
